## Startup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from hmmlearn import hmm

import os
import pickle

In [2]:
random_state=42
np.random.seed(random_state)

In [3]:
from scripts.params import get_params

params = get_params()

## Data Retrieval

In [4]:
dataroute=os.path.join("..",  "data")
dumproute=os.path.join("..",  "dump")
resultsroute=os.path.join("..",  "results")

In [25]:
name=f'finaldf_train_{params["tablename"]}.pickle'
filename=os.path.join(dataroute, name)
with open(filename, 'rb') as handle:
    df=pickle.load(handle)


In [26]:
df.head()

^MERV_rets  ^MERV_log_rets  ^MERV_gk_vol  GGAL.BA_rets  \
2013-01-03    0.007552        0.007524      0.000129      0.010616   
2013-01-04    0.007092        0.007067      0.000158     -0.006303   
2013-01-07   -0.001035       -0.001035      0.000022      0.002114   
2013-01-08    0.008285        0.008251      0.000082     -0.008439   
2013-01-09    0.017826        0.017669      0.000273      0.000000   

            GGAL.BA_log_rets  GGAL.BA_gk_vol  GGAL_rets  GGAL_log_rets  \
2013-01-03          0.010560        0.000677  -0.012748      -0.012830   
2013-01-04         -0.006323        0.000208  -0.010043      -0.010094   
2013-01-07          0.002112        0.000063  -0.014493      -0.014599   
2013-01-08         -0.008474        0.000153  -0.016176      -0.016309   
2013-01-09          0.000000        0.000000   0.011958       0.011887   

            GGAL_gk_vol  YPFD.BA_rets  ...  BBAR.BA_gk_vol  BBAR_rets  \
2013-01-03     0.001228     -0.006863  ...        0.000169  -0.005725   
2013-01-04     0.000554      0.004936  ...        0.000406  -0.019194   
2013-01-07     0.000517      0.010805  ...        0.000492   0.015655   
2013-01-08     0.001085      0.049563  ...        0.000438  -0.015414   
2013-01-09     0.005238      0.000000  ...        0.000000  -0.003914   

            BBAR_log_rets  BBAR_gk_vol  USD_rets  USD_log_rets  USD_gk_vol  \
2013-01-03      -0.005742     0.000960  0.008830      0.008791    0.000014   
2013-01-04      -0.019380     0.000635  0.018043      0.017882    0.000133   
2013-01-07       0.015534     0.000511 -0.002488     -0.002492    0.000048   
2013-01-08      -0.015534     0.000642  0.015356      0.015239    0.000064   
2013-01-09      -0.003922     0.000147 -0.008671     -0.008709    0.001065   

            USD_^MERV_rets  USD_^MERV_log_rets  USD_^MERV_gk_vol  
2013-01-03        0.001247            0.001246          0.000129  
2013-01-04       -0.005727           -0.005743          0.000158  
2013-01-07       -0.009769           -0.009817          0.000022  
2013-01-08       -0.001117           -0.001118          0.000082  
2013-01-09        0.017245            0.017098          0.000273  

[5 rows x 39 columns]

In [27]:
tickerlist=params["tickerlist"]

## HMM Training

In [28]:
range_states=range(1,11)
emptydf=pd.DataFrame(columns=["AIC", "BIC"], index=range_states)
emptydf.fillna(np.inf)
results_dict_df={stock:emptydf for stock in tickerlist}

In [29]:
aic_best_model={stock:None for stock in tickerlist}
bic_best_model={stock:None for stock in tickerlist}

aic_best_residuals={stock:None for stock in tickerlist}
bic_best_residuals={stock:None for stock in tickerlist}

In [30]:
for stock in tickerlist:
    columns = [f'{stock}_log_rets', f'{stock}_gk_vol']
    insample_data = df[columns]

    param_dict={
        "covariance_type" : "diag", 
        "n_iter" : 500,
        "random_state" : random_state
        #no voy a usar startprob_prior por devlog 20-06-23
        }

    for nstate in range_states:
        print(stock, nstate)
        model = hmm.GaussianHMM(n_components= nstate, **param_dict, verbose=False)
        results = model.fit(insample_data)

        # TODO: aca tengo que poner un check de model convergence
        if results.monitor_.converged:
            try:
                results_dict_df[stock].loc[nstate, "AIC"]=model.aic(insample_data)
                results_dict_df[stock].loc[nstate, "BIC"]=model.bic(insample_data)
            except ValueError:
                pass

^MERV 1


Model is not converging.  Current: 18854.600714436052 is not greater than 18855.73073827267. Delta is -1.1300238366166013
Model is not converging.  Current: 18150.450606484752 is not greater than 18151.01274767698. Delta is -0.5621411922293191
Model is not converging.  Current: 18859.18589914981 is not greater than 18864.433488621307. Delta is -5.247589471498941


^MERV 2
^MERV 3
^MERV 4
^MERV 5
^MERV 6
^MERV 7
^MERV 8
^MERV 9


Model is not converging.  Current: 18906.15286542906 is not greater than 18906.406794253573. Delta is -0.253928824513423
Model is not converging.  Current: 18184.342352220032 is not greater than 18184.373920656522. Delta is -0.03156843649048824


^MERV 10
GGAL.BA 1
GGAL.BA 2


Model is not converging.  Current: 17746.98884698709 is not greater than 17749.887170814392. Delta is -2.898323827303102


GGAL.BA 3
GGAL.BA 4


Model is not converging.  Current: 17767.73885078343 is not greater than 17768.03631132637. Delta is -0.2974605429408257


GGAL.BA 5


Model is not converging.  Current: 17747.379395550182 is not greater than 17748.469048154293. Delta is -1.0896526041105972


GGAL.BA 6
GGAL.BA 7


Model is not converging.  Current: 17148.048118381874 is not greater than 17149.571333818458. Delta is -1.523215436583996
Model is not converging.  Current: 17741.233619404436 is not greater than 17743.302334055254. Delta is -2.068714650817128


GGAL.BA 8
GGAL.BA 9


Model is not converging.  Current: 17726.799416526428 is not greater than 17726.836410269803. Delta is -0.03699374337520567


GGAL.BA 10
GGAL 1
GGAL 2


Model is not converging.  Current: 17376.148806625493 is not greater than 17376.15673811304. Delta is -0.007931487547466531
Model is not converging.  Current: 17419.951308954038 is not greater than 17421.03224070274. Delta is -1.0809317487037333
Model is not converging.  Current: 16871.99468009358 is not greater than 16872.01866329594. Delta is -0.02398320236170548
Model is not converging.  Current: 17384.47270583429 is not greater than 17395.592259275767. Delta is -11.119553441476455


GGAL 3
GGAL 4
GGAL 5
GGAL 6


Model is not converging.  Current: 16507.51264994687 is not greater than 16509.147236094755. Delta is -1.6345861478839652


GGAL 7
GGAL 8
GGAL 9
GGAL 10


Model is not converging.  Current: 17388.679891260814 is not greater than 17388.696415755858. Delta is -0.016524495043995557
Model is not converging.  Current: 17800.58434680398 is not greater than 17802.604045122986. Delta is -2.019698319007148
Model is not converging.  Current: 17223.111725584055 is not greater than 17224.078189622516. Delta is -0.9664640384617087
Model is not converging.  Current: 17834.527199608863 is not greater than 17834.550895870856. Delta is -0.023696261992881773


YPFD.BA 1
YPFD.BA 2
YPFD.BA 3
YPFD.BA 4
YPFD.BA 5


c:\Users\alfredo.sampron\AppData\Local\miniconda3\envs\hmm\Lib\site-packages\hmmlearn\hmm.py:340: RuntimeWarning: invalid value encountered in divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because 

YPFD.BA 6
YPFD.BA 7
YPFD.BA 8


Model is not converging.  Current: 17805.326376383062 is not greater than 17811.65090952189. Delta is -6.324533138827974


YPFD.BA 9


Model is not converging.  Current: 17780.781484340816 is not greater than 17785.09311621757. Delta is -4.311631876753381
Model is not converging.  Current: 17647.14483585503 is not greater than 17648.976865823697. Delta is -1.8320299686674844
Model is not converging.  Current: 17103.254564681993 is not greater than 17103.695503924708. Delta is -0.4409392427151033
Model is not converging.  Current: 17736.51869181244 is not greater than 17740.285656396263. Delta is -3.766964583825029


YPFD.BA 10
YPF 1
YPF 2
YPF 3
YPF 4


Model is not converging.  Current: 17117.476683799392 is not greater than 17118.65170713462. Delta is -1.175023335228616
Model is not converging.  Current: 17135.303468956972 is not greater than 17142.596637304305. Delta is -7.293168347332539
Model is not converging.  Current: 17101.753231650084 is not greater than 17103.263201392452. Delta is -1.509969742368412


YPF 5
YPF 6
YPF 7
YPF 8


Model is not converging.  Current: 17627.22497226015 is not greater than 17629.22754421112. Delta is -2.0025719509721966


YPF 9
YPF 10


c:\Users\alfredo.sampron\AppData\Local\miniconda3\envs\hmm\Lib\site-packages\hmmlearn\hmm.py:340: RuntimeWarning: invalid value encountered in divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because 

EDN.BA 1
EDN.BA 2
EDN.BA 3


Model is not converging.  Current: 16662.54021481957 is not greater than 16662.987619628973. Delta is -0.4474048094016325


EDN.BA 4
EDN.BA 5
EDN.BA 6


Model is not converging.  Current: 17064.541553559066 is not greater than 17069.633481501547. Delta is -5.091927942481561


EDN.BA 7
EDN.BA 8
EDN.BA 9


Model is not converging.  Current: 17093.401918079086 is not greater than 17093.59395313576. Delta is -0.19203505667610443


EDN.BA 10


Model is not converging.  Current: 16565.770178800347 is not greater than 16567.146166650873. Delta is -1.375987850526144


EDN 1
EDN 2
EDN 3


Model is not converging.  Current: 16569.60817819587 is not greater than 16571.53116494629. Delta is -1.9229867504182039


EDN 4
EDN 5


Model is not converging.  Current: 16556.64546814014 is not greater than 16557.246782649014. Delta is -0.601314508872747
Model is not converging.  Current: 16578.533843739624 is not greater than 16578.5468281452. Delta is -0.012984405577299185


EDN 6


Model is not converging.  Current: 16123.578011227493 is not greater than 16123.882451481764. Delta is -0.30444025427095767


EDN 7
EDN 8


Model is not converging.  Current: 16406.97428225498 is not greater than 16407.571426234914. Delta is -0.597143979932298


EDN 9
EDN 10


c:\Users\alfredo.sampron\AppData\Local\miniconda3\envs\hmm\Lib\site-packages\hmmlearn\hmm.py:340: RuntimeWarning: invalid value encountered in divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because 

BMA.BA 1
BMA.BA 2
BMA.BA 3
BMA.BA 4
BMA.BA 5


c:\Users\alfredo.sampron\AppData\Local\miniconda3\envs\hmm\Lib\site-packages\hmmlearn\hmm.py:340: RuntimeWarning: invalid value encountered in divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because 

BMA.BA 6
BMA.BA 7
BMA.BA 8
BMA.BA 9


Model is not converging.  Current: 17389.125362292743 is not greater than 17392.336761746483. Delta is -3.211399453739432


BMA.BA 10


Model is not converging.  Current: 17301.880072640575 is not greater than 17304.297173053474. Delta is -2.417100412898435
Model is not converging.  Current: 17365.257578606623 is not greater than 17370.854155502944. Delta is -5.596576896321494


BMA 1
BMA 2
BMA 3
BMA 4
BMA 5


Model is not converging.  Current: 16836.870609729274 is not greater than 16837.902067447147. Delta is -1.0314577178723994
Model is not converging.  Current: 17353.243482582333 is not greater than 17354.21111516984. Delta is -0.9676325875079783


BMA 6
BMA 7


Model is not converging.  Current: 17365.25950397439 is not greater than 17372.507162358776. Delta is -7.247658384385431


BMA 8
BMA 9
BMA 10
BBAR.BA 1
BBAR.BA 2
BBAR.BA 3
BBAR.BA 4
BBAR.BA 5


c:\Users\alfredo.sampron\AppData\Local\miniconda3\envs\hmm\Lib\site-packages\hmmlearn\hmm.py:340: RuntimeWarning: invalid value encountered in divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because 

BBAR.BA 6
BBAR.BA 7


Model is not converging.  Current: 19864.92931539204 is not greater than 19864.96142964032. Delta is -0.03211424827895826


BBAR.BA 8
BBAR.BA 9
BBAR.BA 10


Model is not converging.  Current: 16980.476950533706 is not greater than 16980.912996492345. Delta is -0.4360459586387151
Model is not converging.  Current: 17171.29087869195 is not greater than 17171.495405420286. Delta is -0.20452672833562247


BBAR 1
BBAR 2
BBAR 3


Model is not converging.  Current: 17129.43925706523 is not greater than 17131.721490589865. Delta is -2.2822335246346483
Model is not converging.  Current: 16636.330064094564 is not greater than 16636.986003868267. Delta is -0.6559397737037216
Model is not converging.  Current: 17095.557460314736 is not greater than 17103.462959912966. Delta is -7.905499598229653


BBAR 4
BBAR 5
BBAR 6
BBAR 7


Model is not converging.  Current: 16293.223092897138 is not greater than 16297.273067091071. Delta is -4.04997419393294


BBAR 8
BBAR 9


Model is not converging.  Current: 17104.214221792274 is not greater than 17108.370578230322. Delta is -4.156356438048533


BBAR 10


Model is not converging.  Current: 17093.564168934616 is not greater than 17093.57013615478. Delta is -0.005967220164166065


In [32]:
for stock in tickerlist:
    columns = [f'{stock}_log_rets', f'{stock}_gk_vol']
    insample_data = df[columns]
    
    best_aic_nstate=results_dict_df[stock]["AIC"].astype(float).idxmin()
    best_bic_nstate=results_dict_df[stock]["BIC"].astype(float).idxmin()

    aic_best_model[stock]=hmm.GaussianHMM(n_components = best_aic_nstate, **param_dict).fit(insample_data)
    bic_best_model[stock]=hmm.GaussianHMM(n_components = best_bic_nstate, **param_dict).fit(insample_data)

Model is not converging.  Current: 18150.45060648472 is not greater than 18151.012747677036. Delta is -0.5621411923166306
Model is not converging.  Current: 18150.450606484752 is not greater than 18151.01274767698. Delta is -0.5621411922293191


Model is not converging.  Current: 17746.98884698709 is not greater than 17749.887170814392. Delta is -2.898323827303102
Model is not converging.  Current: 17746.98884698709 is not greater than 17749.887170814392. Delta is -2.898323827303102
Model is not converging.  Current: 17223.11172558406 is not greater than 17224.078189622487. Delta is -0.9664640384253289
Model is not converging.  Current: 17223.111725584044 is not greater than 17224.07818962253. Delta is -0.9664640384871745
Model is not converging.  Current: 17103.254564682 is not greater than 17103.695503924744. Delta is -0.44093924274420715
Model is not converging.  Current: 17103.254564681993 is not greater than 17103.695503924708. Delta is -0.4409392427151033
Model is not converging.  Current: 16565.770178801045 is not greater than 16567.146166650848. Delta is -1.3759878498021862
Model is not converging.  Current: 16565.770178800347 is not greater than 16567.146166650873. Delta is -1.375987850526144
Model is not converging. 

In [34]:
def generate_samples_residuals(model, insample_data, oos_data):
    """
    
    """
    # como el modelo es memoryless, sólo necesito 1 día de observación para saber en qué estado estoy
    # por lo tanto, en vez de complicarme con dos datasets, puedo agregarle el ultimo día de insample_data al ppio de oos_data
    # pseudocodigo
    oos_data=pd.concat([insample_data[-1:], oos_data])
    del insample_data

    samples=pd.DataFrame(columns=oos_data.columns)
    residuals=pd.DataFrame(columns=oos_data.columns)

    # for i=0
    for i in range(1,
                   len(oos_data.index)):
        prev_obs=oos_data[i-1:i]

        todays_obs = oos_data[i:i+1]
        todays_date = todays_obs.index

        state=model.decode(prev_obs)[1][-1]
        # decode()[0] is the log probability, decode()[1] is the sequence of states, [-1] is the last state
        # since we have added the last datum of insample_data to oos_data, then the 
            # TODO: revisar que tenga sentido decodear solo el ultimo día.
            # La alternativa es agregar diez días de insample al principio y usar un decode con diez dias, 
            # me quedo con el ultimo valor del array que maximiza la log-likelihood de la secuencia entera
            # pero como es memoryless, not sure if it makesense
        
        sample = model.sample(n_samples=1, random_state=random_state, currstate=state)[0]
        # sample()[0] is the array with observations of the sampled variables, sample()[1] is the value of the currstate
        sample = pd.DataFrame(data=sample, columns=oos_data.columns, index=todays_date)

        samples=pd.concat([samples, sample])   
        # sampling given state t-1
        # observar realización en t+i
        residual = todays_obs-sample
        
        residuals=pd.concat([residuals, residual])
    
    return samples, residuals

In [36]:
samples, residuals = generate_samples_residuals(aic_best_model[params["index"]], insample_data=insample_data, oos_data=insample_data)

C:\Users\alfredo.sampron\AppData\Local\Temp\ipykernel_47128\3298275339.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  samples=pd.concat([samples, sample])
C:\Users\alfredo.sampron\AppData\Local\Temp\ipykernel_47128\3298275339.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  residuals=pd.concat([residuals, residual])


In [37]:
residuals

BBAR_log_rets  BBAR_gk_vol
2013-01-03      -0.019600     0.000750
2013-01-04      -0.033239     0.000425
2013-01-07       0.001676     0.000302
2013-01-08      -0.029393     0.000432
2013-01-09      -0.017780    -0.000062
...                   ...          ...
2023-05-23       0.016412     0.002582
2023-05-24      -0.002456     0.001250
2023-05-29      -0.013859    -0.000210
2023-05-30       0.004160     0.001003
2023-05-31      -0.036433     0.000394

[2524 rows x 2 columns]

# Guardado de datos

In [38]:
with open(os.path.join(resultsroute, f"""HMM_univ_{params["tablename"]}_aic_bestmodels.pickle"""), "wb") as output_file:
    pickle.dump(aic_best_model, output_file)

with open(os.path.join(resultsroute, f"""HMM_univ_{params["tablename"]}_bic_bestmodels.pickle"""), "wb") as output_file:
    pickle.dump(bic_best_model, output_file)

Los modelos sirven los residuos NO!
https://github.com/alfsn/regime-switching-hmm/issues/27

In [39]:
with open(os.path.join(resultsroute, f"""HMM_univ_{params["tablename"]}_aic_residuals.pickle"""), "wb") as output_file:
    pickle.dump(aic_best_residuals, output_file)

with open(os.path.join(resultsroute, f"""HMM_univ_{params["tablename"]}_bic_residuals.pickle"""), "wb") as output_file:
    pickle.dump(bic_best_residuals, output_file)

In [5]:
models={}
comps=[2,3,4]
datacols=["log_rets","gk_vol"]

for key in data.keys():
    print(key)
    for comp in comps:
        print(comp)
        # TODO: Change from single modelname to [key][comp] nested dict
        modelname=f"{key}_{comp}_model"
        predictionname=f"{key}_{comp}_prediction"
        
        X = data[key][datacols].values.reshape(-1, len(datacols))
        # bivariate
        # log returns and intraday volatility        
        models[modelname]=hmm.GaussianHMM(n_components = comp, #no voy a usar startprob_prior por devlog 20-06-23
                                          covariance_type = "diag", 
                                          n_iter = 500,
                                          random_state = random_state)
        models[modelname].fit(X)
        models[predictionname]=models[modelname].predict(X)

^MERV
2


Model is not converging.  Current: 18846.005278247954 is not greater than 18847.134444221098. Delta is -1.1291659731432446
Model is not converging.  Current: 18142.20139769384 is not greater than 18142.85021337392. Delta is -0.6488156800805882
Model is not converging.  Current: 18905.499058655805 is not greater than 18910.228067216696. Delta is -4.729008560891089


3
4
GGAL
2


Model is not converging.  Current: 18038.2624343628 is not greater than 18038.278369587973. Delta is -0.015935225172142964


3


Model is not converging.  Current: 18073.008746550106 is not greater than 18076.651123470318. Delta is -3.642376920211973


4
GGAL.BA
2
3
4
YPF
2


Model is not converging.  Current: 18304.593473235505 is not greater than 18308.565609003017. Delta is -3.972135767511645
Model is not converging.  Current: 17756.75997738401 is not greater than 17757.203913438225. Delta is -0.443936054216465


3
4


Model is not converging.  Current: 18369.996877026984 is not greater than 18371.30239834195. Delta is -1.3055213149673364


YPFD.BA
2


Model is not converging.  Current: 17798.73799169456 is not greater than 17800.802271672113. Delta is -2.06427997755236


3


Model is not converging.  Current: 17830.629473372283 is not greater than 17832.10104083943. Delta is -1.4715674671460874


4
EDN
2
3


Model is not converging.  Current: 17080.68409876336 is not greater than 17081.789151608813. Delta is -1.1050528454543382
Model is not converging.  Current: 17077.993638007993 is not greater than 17078.23188687198. Delta is -0.2382488639887015


4


Model is not converging.  Current: 17066.381572369566 is not greater than 17070.79977475828. Delta is -4.4182023887151445


EDN.BA
2
3
4


Model is not converging.  Current: 17085.17881044322 is not greater than 17088.685822045376. Delta is -3.507011602156126
Model is not converging.  Current: 17947.094485930793 is not greater than 17949.89450591947. Delta is -2.800019988677377


BMA
2
3


Model is not converging.  Current: 18008.552831003428 is not greater than 18015.43153979727. Delta is -6.878708793843543
Model is not converging.  Current: 17313.299635746713 is not greater than 17317.363432490998. Delta is -4.063796744285355


4
BMA.BA
2
3
4
USD_GGAL
2


Model is not converging.  Current: 21247.674640540492 is not greater than 21249.126418425007. Delta is -1.4517778845147404
Model is not converging.  Current: 20429.677487024546 is not greater than 20429.7433032247. Delta is -0.06581620015276712
Model is not converging.  Current: 21252.80502130624 is not greater than 21252.974330425954. Delta is -0.1693091197121248


3
4
USD_YPF
2
3
4


Model is not converging.  Current: 19728.314739317448 is not greater than 19729.96415354752. Delta is -1.6494142300725798


USD_EDN
2
3


Model is not converging.  Current: 19728.048243246536 is not greater than 19732.180406605632. Delta is -4.132163359096012
Model is not converging.  Current: 21090.250653565647 is not greater than 21091.268319301555. Delta is -1.01766573590794


4
USD_BMA
2
3


Model is not converging.  Current: 20256.947686131723 is not greater than 20257.63595786917. Delta is -0.6882717374464846
Model is not converging.  Current: 21093.16346480629 is not greater than 21093.90066998354. Delta is -0.7372051772508712


4
USD
2
3


Model is not converging.  Current: 21535.656358535536 is not greater than 21535.89830316691. Delta is -0.24194463137246203
Model is not converging.  Current: 19946.186981522354 is not greater than 19948.99284249492. Delta is -2.805860972566734


4
USD_^MERV
2
3


Model is not converging.  Current: 20007.553148425937 is not greater than 20007.581922967158. Delta is -0.028774541220627725


4


In [6]:
# Predict the hidden states corresponding to observed X.
for key in data.keys():
    for comp in comps:
        print(">"*30, key)
        model=models[f"{key}_{comp}_model"]
        prediction=models[f"{key}_{comp}_prediction"]
        print("unique states: ", pd.unique(prediction))
        print("\nStart probabilities:")
        print(model.startprob_)
        print("\nTransition matrix:")
        print(model.transmat_)
        print("\nGaussian distribution means:")
        print(model.means_)
        print("\nGaussian distribution covariances:")
        print(model.covars_)
        print()

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ^MERV
unique states:  [0 1]

Start probabilities:
[9.99999992e-01 7.77089851e-09]

Transition matrix:
[[0.99190044 0.00809956]
 [0.64107689 0.35892311]]

Gaussian distribution means:
[[ 0.0023665   0.00062083]
 [-0.03635524  0.0146091 ]]

Gaussian distribution covariances:
[[[4.65243073e-04 0.00000000e+00]
  [0.00000000e+00 4.63173289e-06]]

 [[1.44224149e-02 0.00000000e+00]
  [0.00000000e+00 1.50614206e-03]]]

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ^MERV
unique states:  [1 0 2]

Start probabilities:
[2.64082753e-02 9.73591725e-01 1.62699196e-11]

Transition matrix:
[[1.36233321e-03 9.98614722e-01 2.29446306e-05]
 [9.77992322e-01 1.06337631e-02 1.13739147e-02]
 [2.70638123e-01 2.45724508e-01 4.83637369e-01]]

Gaussian distribution means:
[[ 0.00147874  0.0006487 ]
 [ 0.00320576  0.00061345]
 [-0.03997792  0.01558215]]

Gaussian distribution covariances:
[[[5.03860880e-04 0.00000000e+00]
  [0.00000000e+00 8.81549832e-06]]

 [[4.56882297e-04 0.00000000e+00]
  [0.00

In [7]:
def plot_close_rets_vol(data, key, comp):
    model=models[f"{key}_{comp}_model"]
    prediction=models[f"{key}_{comp}_prediction"]
    states=set(prediction)

    fig=plt.figure(figsize = (20, 20))
    plt.tight_layout()
    plt.title(f"{key} Close, Log returns and intraday Vol\n{comp} states")

    for subplot, var in zip(range(1,4), ["Close", "log_rets", "gk_vol"]):    
        plt.subplot(3,1,subplot)
        for i in set(prediction):
            state = (prediction == i)
            x = data[key].index[state]
            y = data[key][var].iloc[state]
            plt.plot(x, y, '.')
        plt.legend(states, fontsize=16)
        
        plt.grid(True)
        plt.xlabel("datetime", fontsize=16)
        plt.ylabel(var, fontsize=16)
            
    plt.savefig(os.path.join(resultsroute, "graphs", 
                             f"{comp}_states", 
                             f"{key}_model_{comp}.png"))

In [ ]:
for key in data.keys():
    for comp in comps:
        plot_close_rets_vol(data, key, comp)

## Coefficients 

In [9]:
models.keys()

dict_keys(['^MERV_2_model', '^MERV_2_prediction', '^MERV_3_model', '^MERV_3_prediction', '^MERV_4_model', '^MERV_4_prediction', 'GGAL_2_model', 'GGAL_2_prediction', 'GGAL_3_model', 'GGAL_3_prediction', 'GGAL_4_model', 'GGAL_4_prediction', 'GGAL.BA_2_model', 'GGAL.BA_2_prediction', 'GGAL.BA_3_model', 'GGAL.BA_3_prediction', 'GGAL.BA_4_model', 'GGAL.BA_4_prediction', 'YPF_2_model', 'YPF_2_prediction', 'YPF_3_model', 'YPF_3_prediction', 'YPF_4_model', 'YPF_4_prediction', 'YPFD.BA_2_model', 'YPFD.BA_2_prediction', 'YPFD.BA_3_model', 'YPFD.BA_3_prediction', 'YPFD.BA_4_model', 'YPFD.BA_4_prediction', 'EDN_2_model', 'EDN_2_prediction', 'EDN_3_model', 'EDN_3_prediction', 'EDN_4_model', 'EDN_4_prediction', 'EDN.BA_2_model', 'EDN.BA_2_prediction', 'EDN.BA_3_model', 'EDN.BA_3_prediction', 'EDN.BA_4_model', 'EDN.BA_4_prediction', 'BMA_2_model', 'BMA_2_prediction', 'BMA_3_model', 'BMA_3_prediction', 'BMA_4_model', 'BMA_4_prediction', 'BMA.BA_2_model', 'BMA.BA_2_prediction', 'BMA.BA_3_model', 'BMA.B

In [10]:
for model in models.keys()
    print(model)
    print("Matriz de transicion:")
    print(model.transmat_)
    print("Matriz de emisiones:")
    print(model.means_)

SyntaxError: expected ':' (2188482437.py, line 1)

## HMM Selection

Selecting the Number of States in Hidden Markov Models: Pragmatic Solutions Illustrated Using Animal Movement
https://sci-hub.st/10.1007/s13253-017-0283-8